export const playerBackgroundColors: { color: string; name: string }[] = [
    {color: '#A569BD', name: 'Amethyst Purple'},
    {color: '#5DADE2', name: 'Sky Blue'},
    {color: '#48C9B0', name: 'Aqua Green'},
    {color: '#F4D03F', name: 'Sunflower Yellow'},
    {color: '#DC7633', name: 'Burnt Orange'},
    {color: '#AF7AC5', name: 'Lavender Purple'},
    {color: '#5499C7', name: 'Steel Blue'},
    {color: '#45B39D', name: 'Teal Green'},
    {color: '#F5B041', name: 'Goldenrod'},
    {color: '#D35400', name: 'Pumpkin Orange'},
    {color: '#7D3C98', name: 'Deep Violet'},
    {color: '#1F618D', name: 'Deep Ocean Blue'},
    {color: '#117A65', name: 'Emerald Green'},
    {color: '#B7950B', name: 'Mustard Yellow'},
    {color: '#873600', name: 'Chestnut Brown'},
    {color: '#6C3483', name: 'Grape Purple'},
    {color: '#154360', name: 'Midnight Blue'},
    {color: '#0E6655', name: 'Forest Green'},
    {color: '#9A7D0A', name: 'Olive Yellow'},
    {color: '#6E2C00', name: 'Dark Copper'},
    {color: '#512E5F', name: 'Plum Purple'},
    {color: '#1A5276', name: 'Denim Blue'},
    {color: '#0B5345', name: 'Pine Green'},
    {color: '#7E5109', name: 'Bronze'},
    {color: '#4D2600', name: 'Mahogany Brown'}
];